# Review Dot Product

Solve the following:

$\begin{bmatrix}
4&5\\6&7\\8&9\\
\end{bmatrix}
\cdot
\begin{bmatrix}
2\\3\\
\end{bmatrix}
$

In [1]:
import numpy as np
X = np.array([[4,5], [6,7], [8,9]])
X

array([[4, 5],
       [6, 7],
       [8, 9]])

In [4]:
c = np.array([2, 3]).reshape(-1,1)
c

array([[2],
       [3]])

In [5]:
X @ c

array([[23],
       [33],
       [43]])

In [6]:
np.dot(X, c)

array([[23],
       [33],
       [43]])

In [7]:
X.dot(c)

array([[23],
       [33],
       [43]])

In [ ]:
# np.dot(M, v), row_dot(M, v), and col_dot(M, v) are all the same

# Dot Product: Two Perspectives

## Row Picture

Do dot product one row at a time.

$\begin{bmatrix}
4&5\\6&7\\8&9\\
\end{bmatrix}
\cdot
\begin{bmatrix}
2\\3\\
\end{bmatrix}
=
\begin{bmatrix}
(4*2)+(5*3)\\
(6*2)+(7*3)\\
(8*2)+(9*3)\\
\end{bmatrix}
=
\begin{bmatrix}
23\\
33\\
43\\
\end{bmatrix}
$

In [14]:
def row_dot(M, v):
    v = v.reshape(-1)
    result = []
    for row_idx in range(len(M)):
        row = M[row_idx]
        y = 0
        for i in range(len(row)):
            y += row[i] * v[i]
        result.append(y)
    return np.array(result).reshape(-1,1)
        
row_dot(X, c)

array([[23],
       [33],
       [43]])

## Column Picture

$\begin{bmatrix}
c_0&c_1&c_2\\
\end{bmatrix}
\cdot
\begin{bmatrix}
x\\y\\z\\
\end{bmatrix}
=(c_0*x) + (c_1*y) + (c_2*z)
$

Dot product takes a **linear combination** of columns.

$\begin{bmatrix}
4&5\\6&7\\8&9\\
\end{bmatrix}
\cdot
\begin{bmatrix}
2\\3\\
\end{bmatrix}
=
\begin{bmatrix}
4\\6\\8\\
\end{bmatrix}*2
+
\begin{bmatrix}
5\\7\\9\\
\end{bmatrix}*3
=
\begin{bmatrix}
23\\
33\\
43\\
\end{bmatrix}
$

In [22]:
def col_dot(M, v):
    v = v.reshape(-1)
    result = np.zeros((len(M), 1))
    for col_idx in range(M.shape[1]):
        col = M[:, col_idx].reshape(-1,1)
        result += col * v[col_idx]
    return result
        
col_dot(X, c)

array([[23.],
       [33.],
       [43.]])