# Overview

1. use case for dot product
2. one's column
3. matrix dot vector

$\begin{bmatrix}
1 & 2 \\ 3 & 4\\
\end{bmatrix}
\cdot
\begin{bmatrix}
10 \\ 1 \\
\end{bmatrix}$

In [1]:
import pandas as pd
import numpy as np

In [2]:
houses = pd.DataFrame([[2,1,1985],
                       [3,1,1998],
                       [4,3,2005],
                       [4,2,2020]],
                      columns=["beds", "baths", "year"])
houses

beds  baths  year
0     2      1  1985
1     3      1  1998
2     4      3  2005
3     4      2  2020

In [28]:
# take row (as Series)
# return estimated price (in thousands)
def predict_price(house):
    return ((house["beds"]*42.3) + (house["baths"]*10) + 
            (house["year"]*1.67) - 3213)

predict_price(houses.iloc[0])

196.54999999999973

In [24]:
c = np.array([42.3, 10, 1.67]).reshape(-1, 1)
b = -3213
c

array([[42.3 ],
       [10.  ],
       [ 1.67]])

In [25]:
X = houses.values
X

array([[   2,    1, 1985],
       [   3,    1, 1998],
       [   4,    3, 2005],
       [   4,    2, 2020]])

In [29]:
h0 = X[0:1, :]
h1 = X[1:2, :]
h2 = X[2:3, :]
h3 = X[3:4, :]
h0

array([[   2,    1, 1985]])

In [31]:
print(h0 @ c + b)
print(h1 @ c + b)
print(h2 @ c + b)
print(h3 @ c + b)

[[196.55]]
[[260.56]]
[[334.55]]
[[349.6]]


In [32]:
X

array([[   2,    1, 1985],
       [   3,    1, 1998],
       [   4,    3, 2005],
       [   4,    2, 2020]])

In [35]:
X @ c + b

array([[196.55],
       [260.56],
       [334.55],
       [349.6 ]])

In [41]:
houses["const"] = 1
houses

beds  baths  year  const
0     2      1  1985      1
1     3      1  1998      1
2     4      3  2005      1
3     4      2  2020      1

In [42]:
X = houses.values
X

array([[   2,    1, 1985,    1],
       [   3,    1, 1998,    1],
       [   4,    3, 2005,    1],
       [   4,    2, 2020,    1]])

In [43]:
c = np.array([42.3, 10, 1.67, -3213]).reshape(-1, 1)
c

array([[ 4.230e+01],
       [ 1.000e+01],
       [ 1.670e+00],
       [-3.213e+03]])

In [44]:
X @ c

array([[196.55],
       [260.56],
       [334.55],
       [349.6 ]])

In [45]:
houses["price_est"] = X @ c
houses

beds  baths  year  const  price_est
0     2      1  1985      1     196.55
1     3      1  1998      1     260.56
2     4      3  2005      1     334.55
3     4      2  2020      1     349.60