In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, recall_score, precision_score
from sklearn.metrics import accuracy_score, balanced_accuracy_score

# Multi-Class Metrics

In [5]:
actual =    ["dog", "dog", "dog", "dog", "cat", "cat", "cat", "cat", "mouse", "mouse"] * 199
predicted = ["dog", "dog", "dog", "dog", "cat", "dog", "cat", "dog", "mouse", "mouse"] * 199
actual += ["horse"] * 10
predicted += ["dog"] * 9 + ["horse"]

labels = ["dog", "cat", "mouse", "horse"]
cm = confusion_matrix(actual, predicted, labels)
cm = pd.DataFrame(cm, index=labels, columns=labels)
cm

dog  cat  mouse  horse
dog    796    0      0      0
cat    398  398      0      0
mouse    0    0    398      0
horse    9    0      0      1

In [6]:
accuracy_score(actual, predicted)

0.7965

In [8]:
cm.loc["horse", "horse"] / cm.loc["horse"].sum()

0.1

In [13]:
recall_score(actual, predicted, average=None, labels=labels)

array([1. , 0.5, 1. , 0.1])

In [14]:
recall_score(actual, predicted, average=None, labels=labels).mean()

0.65

In [15]:
balanced_accuracy_score(actual, predicted)

0.65

In [16]:
precision_score(actual, predicted, average=None, labels=labels)

array([0.66167914, 1.        , 1.        , 1.        ])

# Binary Classification Metrics

Unless otherwise specified, "precision" and "recall" refer to those metrics for the positive class when we're doing binary classification.

In [18]:
actual = [False, True, True, True, True, False, False, True, True, True, True, True, True]
predicted = [False, True, True, True, True, True, True, False, False, False, True, True, True]
confusion_matrix(actual, predicted)

array([[1, 2],
       [3, 7]])

In [19]:
recall_score(actual, predicted, average=None, labels=[False, True])

array([0.33333333, 0.7       ])

In [21]:
recall_score(actual, predicted)

0.7