# Column Space of a Matrix

Definition: the *column space* of a matrix is the set of all linear combinations of that matrix's columns.

In [2]:
import numpy as np
A = np.array([
    [1,100],
    [2,10],
    [3,0]
])
B = np.array([
    [1,0],
    [0,2],
    [0,3],
    [0,0]
])

$A = \begin{bmatrix}
1&100\\
2&10\\
3&0\\
\end{bmatrix}$

In [3]:
A

array([[  1, 100],
       [  2,  10],
       [  3,   0]])

In [8]:
c = np.array([-1, 100]).reshape(-1,1) # coef
A @ c # whatever this produces is in the column space, no matter how you change c

array([[9999],
       [ 998],
       [  -3]])

What vectors are in the column space of B?

$B = \begin{bmatrix}
1&0\\
0&2\\
0&3\\
0&0\\
\end{bmatrix}$

$a=\begin{bmatrix}
2\\
2\\
3\\
0
\end{bmatrix}, b=\begin{bmatrix}
0\\
0\\
0\\
1
\end{bmatrix}, c=\begin{bmatrix}
-10\\
0\\
0\\
0
\end{bmatrix}, d=\begin{bmatrix}
0\\
-2\\
3\\
0
\end{bmatrix}, e=\begin{bmatrix}
-1\\
2\\
3\\
0
\end{bmatrix}$

In [18]:
# in the column space of B: a, c, e
# not in the column space: b, d
c = np.array([-1, 1]).reshape(-1,1) # coef
B @ c

array([[-1],
       [ 2],
       [ 3],
       [ 0]])